<a href="https://colab.research.google.com/github/MURALAAYYAPPA/Machine-Learning/blob/main/Naive_Bayes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv("titanic (1).csv")
df

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [5]:
target=df.Survived
inputs=df.drop('Survived',axis='columns')

In [6]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [7]:
input = pd.concat([inputs,dummies],axis='columns')
input.head(4)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False

In [12]:
input.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [13]:
input.columns[input.isna().any()]

Index(['Age'], dtype='object')

In [14]:
input.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [15]:
input.Age = input.Age.fillna(input.Age.mean())
input.head(5)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input,target,test_size=0.2)

In [17]:
len(X_train)

712

In [18]:
len(X_test)

179

In [19]:
len(input)

891

In [20]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [21]:
model.fit(X_train,y_train)

GaussianNB()

In [22]:
model.score(X_test,y_test)

0.7541899441340782

In [24]:
X_test[:10]

     Pclass        Age      Fare  female
137       1  37.000000   53.1000   False
744       3  31.000000    7.9250   False
666       2  25.000000   13.0000   False
498       1  25.000000  151.5500    True
851       3  74.000000    7.7750   False
405       2  34.000000   21.0000   False
202       3  34.000000    6.4958   False
47        3  29.699118    7.7500    True
748       1  19.000000   53.1000   False
870       3  26.000000    7.8958   False

In [25]:
y_test

137    0
744    1
666    0
498    0
851    0
      ..
169    0
569    1
190    1
191    0
799    0
Name: Survived, Length: 179, dtype: int64

In [26]:
model.predict(X_test[:10])

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0])

In [27]:
model.predict_proba(X_test[:10])

array([[6.90587052e-01, 3.09412948e-01],
       [9.68708586e-01, 3.12914141e-02],
       [9.30262390e-01, 6.97376097e-02],
       [3.51241578e-05, 9.99964876e-01],
       [9.50734227e-01, 4.92657734e-02],
       [9.36786048e-01, 6.32139519e-02],
       [9.69409415e-01, 3.05905853e-02],
       [3.93929153e-01, 6.06070847e-01],
       [6.28753719e-01, 3.71246281e-01],
       [9.66381776e-01, 3.36182237e-02]])